# Generated by Django 4.1.2 on 2022-10-06 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Code', models.IntegerField()),
                ('Item_name', models.CharField(max_length=150)),
                ('Item_Measurement', models.CharField(choices=[('N', 'Nos'), ('M', 'Meter'), ('KG', 'Kilo Gram'), ('KM', 'Kilo Meter')], max_length=2)),
                ('Item_stock', models.IntegerField()),
                ('Item_Image', models.ImageField(upload_to='uploads/')),
                ('Supplier_name', models.CharField(max_length=150)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Requisition_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
